---
# file: handlers/main.yml
#

- name: restart ganglia-monitor
  sudo: True
  service: name=ganglia-monitor state=restarted

- name: stop ganglia-monitor
  sudo: True
  service: name=ganglia-monitor state=stopped